In [1]:
#Xây dựng mảng các luỹ thừa của 2 nhỏ hơn 1025
import numpy as np

a = np.arange(0, 11)
b = 2
c = b**a
c

array([   1,    2,    4,    8,   16,   32,   64,  128,  256,  512, 1024],
      dtype=int32)

In [2]:
# Xây dựng mảng gồm 10 phần tử, trong đó 9 phần tử đầu bằng 3, phần tử cuối cùng bằng 1.5.
import numpy as np
a = np.ones(9)*3
a = np.append(a, 1.5)
a

array([3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 1.5])

In [3]:
#Thay toàn bộ các phần tử của mảng bằng trung bình cộng các phần tử trong mảng đó, sử dụng vòng for. Hàm này không trả về biến nào mà chỉ thay đổi các giá trị của biến đầu vào x.
import numpy as np
def fix(arr):
    m = np.mean(arr)
    for i in range(len(arr)):
        arr[i] = m

a = np.arange(0, 11)
fix(a)
a

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [4]:
#Cho trước một số tự nhiên n. Tạo một mảng có n phần tử mà các phần tử có chỉ số chẵn (bắt đầu từ 0) là một cấp số cộng bắt đầu từ 2, công sai bằng -0.5; các phần tử có chỉ số lẻ bằng -1.
import numpy as np
def special_arr(n):
    arr = np.ones(n)*-1
    for i in range(0, n, 2):
        arr[i] = 2 + i*-0.5/2
    return arr
special_arr(4)


array([ 2. , -1. ,  1.5, -1. ])

In [5]:
#Cho một mảng 1 chiều x, tính mảng y và z sao cho y[i] = pi/2 - x[i] và z[i] = cos(x[i]) - sin(x[i]). Sau đó trả về tổng các phần tử của z
x = np.arange(0, 10)
y = np.pi/2 - x
z = np.cos(x) - np.sin(x)
y



array([ 1.57079633,  0.57079633, -0.42920367, -1.42920367, -2.42920367,
       -3.42920367, -4.42920367, -5.42920367, -6.42920367, -7.42920367])

In [6]:
x = np.arange(0, 10)
y = np.exp(x)
sum = np.sum(y)
soft_max = y / sum
soft_max

array([7.80134161e-05, 2.12062451e-04, 5.76445508e-04, 1.56694135e-03,
       4.25938820e-03, 1.15782175e-02, 3.14728583e-02, 8.55520989e-02,
       2.32554716e-01, 6.32149258e-01])

In [7]:
#Với một số tự nhiên n, hãy viết hàm trả về ma trận có dạng đường chéo phụ ngay dưới đường chéo chính nhận các giá trị từ 1 đến n. Các thành phần là kiểu số nguyên.
import numpy as np
def arr(n):
    return np.diag(np.arange(1,n+1), k=-1)
arr(6)

array([[0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0]])

In [8]:
#Cho một ma trận A, viết hàm myfunc tính tổng các phần tử trên các cột có chỉ số chẵn (0, 2, 4, ...) của ma trận đó. Ví dụ:
import numpy as np
def myfunc(a):
    return np.sum(a[:,::2])
A = np.array([[5, 6], [3, 4]])
myfunc(A)

8

In [9]:
# Viết hàm myfunc tính tổng tất cả các phần tử có cả hai chỉ số đều chẵn của một ma trận A bất kỳ.
import numpy as np
def myfunc(A):
   return np.sum(A[::2,::2])
A = np.array([[5, 6, 4], [3, 4, 9]])
myfunc(A)#5+4

9

In [10]:
#Viết hàm norm_fro(A) tính Frobenius norm của một ma trận bất kỳ.
def norm_fro(A):
    B = A**2
    return (np.sqrt(np.sum(B)))
A = np.array([[5, 6, 4], [3, 4, 9]])
norm_fro(A)

13.527749258468683

In [11]:
#Viết hàm dist_fro tính bình phương Frobenious norm của hiệu hai ma trận được mô tả bởi hai mảng đó.
import numpy as np

A = np.array([[1, 3], [2, 5]])
def norm_fro(A):
    B = A**2
    return (np.sqrt(np.sum(B)))
def dis_fro(A, B):
    C = A - B
    return norm_fro(C)
A = np.array([[1, 5], [2, 3]])
B = np.array([[5, 8], [7, 3]])
dis_fro(A, B)

7.0710678118654755

In [12]:
import numpy as np
a = np.transpose(np.arange(1,13).reshape(3, 4).reshape(4,-1,order='F'))
a

array([[ 1,  5,  9,  2],
       [ 6, 10,  3,  7],
       [11,  4,  8, 12]])

In [13]:
import numpy as np
def fro_trace(A):
    B = np.transpose(A)
    return np.trace(A@B)
A = np.array([[ 1,  5,  9,  2],
       [ 6, 10,  3,  7],
       [11,  4,  8, 12]])
fro_trace(A)

650

In [14]:
import numpy as np
def create_array(a, b, m, n):
    return np.random.uniform(a, b, (m, n))
create_array(2, 3, 5, 6)


array([[2.01077438, 2.95959397, 2.16978207, 2.87361778, 2.85834991,
        2.51754057],
       [2.84300996, 2.55935366, 2.24246566, 2.90913529, 2.71168059,
        2.41342212],
       [2.40407848, 2.53828295, 2.85094331, 2.88844782, 2.87210736,
        2.82334776],
       [2.02660925, 2.11575423, 2.10253451, 2.00286843, 2.42386244,
        2.23830624],
       [2.88905053, 2.34598351, 2.13249763, 2.71985374, 2.1807158 ,
        2.87972451]])

In [15]:
import numpy as np

def create_normal_array(a, s, m, n):
    return np.random.normal(a, s, (m, n))
create_normal_array(2, 4, 4, 5)

array([[-5.69921892,  3.07536317,  0.67648206, -3.03552891,  4.60781619],
       [ 3.31616353, -4.2362364 ,  0.67245308,  2.08393773,  2.73711829],
       [-2.33695856, -2.06877799, -0.74861526, -2.34650094,  4.17446849],
       [ 3.05722066, -2.7169952 , -2.53147862,  2.95754368, -1.48572625]])

In [16]:
import numpy as np

def sample_no_replace(N, k):
    return np.random.choice(N, k, replace = False)
sample_no_replace(50, 20)

array([24, 17, 19,  8, 13, 18, 40, 15, 10, 48, 12, 22, 16, 41, 39, 14, 23,
       44, 26, 37])